txt = input('digite algo: ')
print('o tipo dele é',type(txt))
print('só tem espaços?',txt.isspace())
print('é numero? ',txt.isnumeric())
print('é alfabetico? ',txt.isalpha())
print('é alfanumerico? ',txt.isalnum())
print('está maiúsculo? ',txt.isupper())
print('minúscula? ',txt.islower())
print('capitalizada? ',txt.istitle()) 